import { Car } from "./Car";

export const cars: Car[] = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    tier: "Sport",
    year: "2022",
    type: "Sedan",
    price: 20000,
    mileage: "5200",
    image: "../images/toyotaCorolla2022.webp",
    certifiedPreOwned: true,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "4-Cyl, 1.8 Liter",
      "Black Interior Color",
      "Black Exterior Color",
      "4 Door Sedan",
      "30 City / 38 Hwy",
      "Automatic, CVT",
      "FWD",
      "2 Keys",
      "VIN: 5YFEPMAE5MP149583",
      "5 seats",
      "Stock #: 2001966868",
    ],
    features: [
      "Daytime Running Lights",
      "LED Headlamps",
      "Power Door Locks",
      "Dynamic Cruise Control",
      "Power Windows",
      "Air Conditioning",
      "Remote Trunk Release",
      "Keyless Entry",
      "Traction Control",
      "Stability Control",
      "Vehicle Dynamic Control",
      "Hill Start Assist Control",
      "ABS (4-Wheel)",
    ],
  },
  {
    id: 2,
    make: "BMW",
    model: "X5",
    tier: "xDrive35i Premium",
    year: "2013",
    type: "SUV",
    price: 24900,
    mileage: "56200",
    image: "../images/bmwx52013.webp",
    certifiedPreOwned: false,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "6-Cyl, Turbo, 3.0L",
      "Beige Interior Color",
      "Black Exterior Color",
      "4 Door SUV",
      "16 City / 23 Hwy",
      "Auto, 8-Spd Spt Stptrnc",
      "AWD",
      "1 Key",
      "VIN: 5UXZV4C53DL993214",
      "5 seats",
      "Stock #: 2001824105",
    ],
    features: [
      "Child safety rear door locks",
      "Roof rails",
      "Active Head Restraints in front seats",
      "Active-charcoal micro-filter ventilation",
      "Adaptive Brake Lights",
      "Automatic tilt-down of right outside mirror for visibility of curb when backing up",
    ],
  },
  {
    id: 3,
    make: "Ford",
    model: "F150 Super Cab",
    tier: "XL 6 1/2 ft",
    year: "2018",
    type: "Truck",
    price: 30590,
    mileage: "47338",
    image: "../images/fordf1502018.webp",
    certifiedPreOwned: true,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "V6, Flex Fuel, 3.3 Liter",
      "Gray Interior Color",
      "Blue Exterior Color",
      "4 Door Truck",
      "Automatic",
      "4WD",
      "2 Keys",
      "VIN: 1FTEX1EB5JFE45978",
      "5 seats",
      "Stock #: 2001874121",
    ],
    features: [
      "EASY FUEL CAPLESS FILLER",
      "MANUAL FOLD POWER MIRRORS",
      "CRUISE CONTROL",
      "ILLUMINATED ENTRY",
      "TILT/TELESCOPE STR COLUMN",
      "MYKEY",
      "REAR VIEW CAMERA",
      "AIRBAGS - FRONT SEAT MOUNTED SIDE IMPACT",
      "TIRE PRESSURE MONITOR SYS",
      "3YR/36,000 BUMPER / BUMPER",
      "5YR/60,000 POWERTRAIN",
      "HEADLAMPS - AUTOLAMP (ON/OFF)",
      "1TOUCH UP/DOWN DR/PASS WIN",
      "PERIMETER ALARM",
      "SOS POST CRASH ALERT SYS",
      "TRAILER SWAY CONTROL",
    ],
  },
  {
    id: 4,
    make: "Mini",
    model: "Cooper",
    tier: "S All4",
    year: "2013",
    type: "Hunchback",
    price: 18890,
    mileage: "63000",
    image: "../images/minicooper2013.webp",
    certifiedPreOwned: false,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "4-Cyl, 1.6L",
      "Black Interior Color",
      "Red Exterior Color",
      "2 Door Coupe",
      "28 City / 36 Hwy",
      "CVT",
      "FWD",
      "2 Keys",
      "VIN: WMWSX1C5XET507914",
      "2 seats",
      "Stock #: 2001805894",
    ],
    features: [
      "Electric Power-Assist Speed-Sensing Steering",
      "Front And Rear Anti-Roll Bars",
      "Front-Wheel Drive",
      "Gas-Pressurized Shock Absorbers",
      "Single Stainless Steel Exhaust w/Chrome Tailpipe Finisher",
    ],
  },
  {
    id: 5,
    make: "Chevrolet",
    model: "Camaro",
    tier: "LT",
    year: "2016",
    type: "Coupe",
    price: 23990,
    mileage: "72000",
    image: "../images/chevroletcamaro2016.webp",
    certifiedPreOwned: false,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      " 4-Cyl, Turbo, 2.0L",
      "Black Interior Color",
      "Gray Exterior Color",
      "2 Door Coupe",
      "22 City / 31 Hwy",
      "Automatic, 8 speed",
      "RWD",
      "2 Keys",
      "VIN: 1G1FB1RX7G0160227",
      "4 seats",
      "Stock #: 2002009235",
    ],
    features: [
      "Brakes, 4-wheel antilock, 4-wheel disc",
      "Floor mats, carpeted front",
      "Rear Vision Camera",
      "Shift knob, leather-wrapped",
      "OnStar Basic Plan for 5 years including limited RemoteLink mobile app services, Advanced Diagnostics and Dealer Maintenance Notification (Basic Plan available for 5 years from the date of vehicle delivery, and is transferable. Does not include Emergency, Security or Navigation services.)",
    ],
  },
  {
    id: 6,
    make: "Chevrolet",
    model: "Corvette",
    tier: "Stringray",
    year: "2021",
    type: "Convertable",
    price: 104990,
    mileage: "3930",
    image: "../images/chevroletcorvette2021.webp",
    certifiedPreOwned: true,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "8-Cyl, 6.2L",
      "Other Interior Color",
      "Silver Exterior Color",
      "2 Door Convertible",
      "15 City / 27 Hwy",
      "Automatic, 8 speed",
      "RWD",
      "2 Keys",
      "VIN: 1G1YC3D41M5115409",
      "2 seats",
      "Stock #: 2001987723",
    ],
    features: [
      "Cruise control, electronic with set and resume speed",
      "Remote Vehicle Starter System",
      "Seat adjuster, driver 8-way power",
      "Wipers, front intermittent",
      "Daytime Running Lamps",
    ],
  },
  {
    id: 7,
    make: "Ford",
    model: "F150",
    tier: "XLT 5",
    year: "2013",
    type: "Truck",
    price: 24590,
    mileage: "81721",
    image: "../images/fordf1502013.webp",
    certifiedPreOwned: false,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "V6, Flex Fuel, 3.3 Liter",
      "Gray Interior Color",
      "Blue Exterior Color",
      "4 Door Truck",
      "Automatic",
      "4WD",
      "2 Keys",
      "VIN: 1FTEX1EB5JFE45978",
      "5 seats",
      "Stock #: 2001874121",
    ],
    features: [
      "EASY FUEL CAPLESS FILLER",
      "MANUAL FOLD POWER MIRRORS",
      "CRUISE CONTROL",
      "ILLUMINATED ENTRY",
      "TILT/TELESCOPE STR COLUMN",
      "MYKEY",
      "REAR VIEW CAMERA",
      "AIRBAGS - FRONT SEAT MOUNTED SIDE IMPACT",
      "TIRE PRESSURE MONITOR SYS",
      "3YR/36,000 BUMPER / BUMPER",
      "5YR/60,000 POWERTRAIN",
      "HEADLAMPS - AUTOLAMP (ON/OFF)",
      "1TOUCH UP/DOWN DR/PASS WIN",
      "PERIMETER ALARM",
      "SOS POST CRASH ALERT SYS",
      "TRAILER SWAY CONTROL",
    ],
  },
  {
    id: 8,
    make: "Chevrolet",
    model: "Colorado",
    tier: "LT",
    year: "2015",
    type: "Truck",
    price: 26990,
    mileage: "77300",
    image: "../images/chevroletcolorado2015.webp",
    certifiedPreOwned: false,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "V6, Flex Fuel, 3.3 Liter",
      "Gray Interior Color",
      "Blue Exterior Color",
      "4 Door Truck",
      "Automatic",
      "4WD",
      "2 Keys",
      "VIN: 1FTEX1EB5JFE45978",
      "5 seats",
      "Stock #: 2001874121",
    ],
    features: [
      "EASY FUEL CAPLESS FILLER",
      "MANUAL FOLD POWER MIRRORS",
      "CRUISE CONTROL",
      "ILLUMINATED ENTRY",
      "TILT/TELESCOPE STR COLUMN",
      "MYKEY",
      "REAR VIEW CAMERA",
      "AIRBAGS - FRONT SEAT MOUNTED SIDE IMPACT",
      "TIRE PRESSURE MONITOR SYS",
      "3YR/36,000 BUMPER / BUMPER",
      "5YR/60,000 POWERTRAIN",
      "HEADLAMPS - AUTOLAMP (ON/OFF)",
      "1TOUCH UP/DOWN DR/PASS WIN",
      "PERIMETER ALARM",
      "SOS POST CRASH ALERT SYS",
      "TRAILER SWAY CONTROL",
    ],
  },
  {
    id: 9,
    make: "Mini",
    model: "Cooper",
    tier: "S",
    year: "2015",
    type: "Convertable",
    price: 24590,
    mileage: "34581",
    image: "../images/minicooper2015.webp",
    certifiedPreOwned: false,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "4-Cyl, 1.6L",
      "Black Interior Color",
      "Red Exterior Color",
      "2 Door Coupe",
      "28 City / 36 Hwy",
      "CVT",
      "FWD",
      "2 Keys",
      "VIN: WMWSX1C5XET507914",
      "2 seats",
      "Stock #: 2001805894",
    ],
    features: [
      "Electric Power-Assist Speed-Sensing Steering",
      "Front And Rear Anti-Roll Bars",
      "Front-Wheel Drive",
      "Gas-Pressurized Shock Absorbers",
      "Single Stainless Steel Exhaust w/Chrome Tailpipe Finisher",
    ],
  },
  {
    id: 10,
    make: "Mercedes-Benz",
    model: "250",
    tier: "CLA",
    year: "2014",
    type: "Coupe",
    price: 23990,
    mileage: "49488",
    image: "../images/mercedesbenz2014.webp",
    certifiedPreOwned: true,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "4-Cyl, 1.8 Liter",
      "Black Interior Color",
      "Black Exterior Color",
      "4 Door Sedan",
      "30 City / 38 Hwy",
      "Automatic, CVT",
      "FWD",
      "2 Keys",
      "VIN: 5YFEPMAE5MP149583",
      "5 seats",
      "Stock #: 2001966868",
    ],
    features: [
      "Daytime Running Lights",
      "LED Headlamps",
      "Power Door Locks",
      "Dynamic Cruise Control",
      "Power Windows",
      "Air Conditioning",
      "Remote Trunk Release",
      "Keyless Entry",
      "Traction Control",
      "Stability Control",
      "Vehicle Dynamic Control",
      "Hill Start Assist Control",
      "ABS (4-Wheel)",
    ],
  },
  {
    id: 11,
    make: "Lincoln",
    model: "MKS",
    tier: "Base",
    year: "2013",
    type: "Sedan",
    price: 19590,
    mileage: "46560",
    image: "../images/lincolnmks2013.webp",
    certifiedPreOwned: true,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "4-Cyl, 1.8 Liter",
      "Black Interior Color",
      "Black Exterior Color",
      "4 Door Sedan",
      "30 City / 38 Hwy",
      "Automatic, CVT",
      "FWD",
      "2 Keys",
      "VIN: 5YFEPMAE5MP149583",
      "5 seats",
      "Stock #: 2001966868",
    ],
    features: [
      "Daytime Running Lights",
      "LED Headlamps",
      "Power Door Locks",
      "Dynamic Cruise Control",
      "Power Windows",
      "Air Conditioning",
      "Remote Trunk Release",
      "Keyless Entry",
      "Traction Control",
      "Stability Control",
      "Vehicle Dynamic Control",
      "Hill Start Assist Control",
      "ABS (4-Wheel)",
    ],
  },
  {
    id: 12,
    make: "Tesla",
    model: "S",
    tier: "Performance",
    year: "2020",
    type: "Sedan",
    price: 92590,
    mileage: "17580",
    image: "../images/teslas2020.webp",
    certifiedPreOwned: true,
    detailedImage:
      "https://vexstockimages.fastly.carvana.io/stockimages/2018_FORD_F150%20SUPER%20CAB_XLT%20PICKUP%204D%206%201/2%20FT_WHITE_stock_desktop_1920x1080.png?v=1645550492.220",
    highlights: [
      "seat controls",
      "Bluetooth",
      "Lane Departure",
      "Infotainment System",
      "Backup Camera",
    ],
    basicInformation: [
      "Dual AC Electric Motors, High Performance Rear",
      "Beige Interior Color",
      "White Exterior Color",
      "4 Door Sedan",
      "104 City / 104 Hwy",
      "Range: 348 miles",
      "Single-Speed Fixed Gear",
      "AWD",
      "1 Key",
      "VIN: 5YJSA1E40LF413842",
      "5 seats",
      "Stock #: 2001958869",
    ],
    features: [
      "Hill Start Assist",
      "ABS (4-Wheel)",
      "Electronic Traction Control",
      "Smart Air Suspension",
    ],
  },
];
